name: tawaj
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  progress_indicators: ^1.0.0
  get: ^4.6.5
  flutter_svg: 1.1.6
  flutter: 
    sdk: flutter
  floating_bottom_navigation_bar: ^1.5.2
  http: ^0.13.5
  carousel_slider: ^4.2.1
  arabic_numbers: ^1.0.0
  flutter_switch: ^0.3.2
  webview_flutter: ^3.0.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.0
  get_storage: ^2.1.1
  flutter_local_notifications: ^8.2.0
  firebase_messaging: ^14.3.0
  firebase_core: ^2.8.0
  firebase_analytics: ^10.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/
  uses-material-design: true

  fonts : 
    - family : ScheherazadeNew
      fonts : 
      - asset: fonts/ScheherazadeNew-Regular.ttf
    - family : Open Sans
      fonts : 
      - asset: fonts/OpenSans-Regular.ttf
      - asset: fonts/OpenSans-Light.ttf
      - asset: fonts/OpenSans-SemiBold.ttf

