// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT2X-E3sEig50qrOQWfSb82d1lwRMM8is',
    appId: '1:545487608935:web:ef27b797e23d7c7b8048c2',
    messagingSenderId: '545487608935',
    projectId: 'alquran-test-a4e27',
    authDomain: 'alquran-test-a4e27.firebaseapp.com',
    storageBucket: 'alquran-test-a4e27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB67G8a3TvqSs0A6MJrN43FQDRT80WOsL4',
    appId: '1:545487608935:android:06e21847db0ec6d08048c2',
    messagingSenderId: '545487608935',
    projectId: 'alquran-test-a4e27',
    storageBucket: 'alquran-test-a4e27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmCkJkpnbb5DZ4KmnId3MlOnDw3cOsMhI',
    appId: '1:545487608935:ios:93c792a8668e51888048c2',
    messagingSenderId: '545487608935',
    projectId: 'alquran-test-a4e27',
    storageBucket: 'alquran-test-a4e27.appspot.com',
    iosClientId: '545487608935-6cpab1039knjnkl5tl6jrktdqphr30a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tawaj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmCkJkpnbb5DZ4KmnId3MlOnDw3cOsMhI',
    appId: '1:545487608935:ios:93c792a8668e51888048c2',
    messagingSenderId: '545487608935',
    projectId: 'alquran-test-a4e27',
    storageBucket: 'alquran-test-a4e27.appspot.com',
    iosClientId: '545487608935-6cpab1039knjnkl5tl6jrktdqphr30a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tawaj',
  );
}
